---
- name: Register Nixtats Agent service status
  stat: 
    path: "/etc/systemd/system/nixstatsagent.service"
  register: service_status

- name: Install Nixtats Agent
  block:
    - name: Download Agent
      get_url: url=https://nixstats.com/nixstatsagent.sh dest=/tmp/nixstatsagent.sh

    - name: Install Agent
      shell: bash /tmp/nixstatsagent.sh {{ nixstats_server_id }} {{ nixstats_user_id }}
      register: agent_install_out
      failed_when: agent_install_out.stderr is not ""
      
    - name: Remove installer
      file: path=/tmp/nixstatsagent.sh state=absent
  when: not service_status.stat.exists

- name: Install Mysql Dependencies
  apt:
    name: python-mysqldb

- name: Setup Nginx NIXStats
  block: 
    - name: Nginx NIXStats to sites available
      template:
        src: nginx.conf.j2
        dest: "{{ nginx_path }}/sites-available/nixstats_nginx.conf"
      notify: reload nginx

    - name: Nginx NIXStats to sites enabled
      file:
        src: "{{ nginx_path }}/sites-available/nixstats_nginx.conf"
        dest: "{{ nginx_path }}/sites-enabled/nixstats_nginx.conf"
        state: link
      notify: reload nginx
  when: nixstats_nginx_enabled or nixstats_phpfpm_enabled

- name: Setup NIXStats php-fpm configuration file 
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/7.3/fpm/pool.d/nixstats.conf
  notify: reload php-fpm
  when: nixstats_phpfpm_enabled

- name: Create rsyslog working directory
  file:
    path: /var/spool/rsyslog/
    state: directory

- name: Create /etc/rsyslog.d/keys directory
  file:
    path: /etc/rsyslog.d/keys
    state: directory

- name: Downloading TLS CA file
  get_url:
    url: https://www.nixstats.com/nixstats.ca
    dest: /etc/rsyslog.d/keys/nixstats.ca

- name: Setup NIXStats rsyslog
  template:
    src: rsyslog.conf.j2 
    dest: /etc/rsyslog.d/31-nixstats.conf
  notify: reload rsyslog

- name: Setup NIXStats rsyslog nginx
  template:
    src: rsyslog-nginx.conf.j2 
    dest: /etc/rsyslog.d/33-nixstats-nginx.conf
  notify: reload rsyslog
  when: nixstats_nginx_enabled

- name: NIXStats configuration
  template:
    src: nixstats.ini.j2
    dest: /etc/nixstats.ini
  notify: reload nixstatsagent